title: perifaCode - comunidade de programação da periferia
email: contato@perifacode.com
description: >- # this means to ignore newlines until "baseurl:"
  Aqui reunimos pessoas que moram em periferias, 
  favelas e guetos do Brasil para criar uma rede de apoio 
  para conseguirmos vencer as barreiras sociais 
  que nos limitam a entrada ou evolução na área de programação.
baseurl: ""
url: "http://perifacode.com"
twitter_username: perifacode
github_username:  perifacode

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
